In [2]:
!pip install openai -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.6/73.6 kB 1.7 MB/s eta 0:00:00

In [3]:
import openai

In [19]:
from getpass import getpass
openai.api_key = getpass()

··········

In [20]:
import pandas as pd

In [21]:
df = pd.read_csv('word.csv')

In [22]:
df

       text
0     "red"
1   "green"
2  "yellow"
3    "blue"
4   "black"

In [23]:
from openai.embeddings_utils import get_embedding
df['embedding'] = df['text'].apply(lambda x: get_embedding(x, engine='text-embedding-ada-002'))

In [25]:
df

       text                                          embedding
0     "red"  [-0.004908404778689146, -0.01628972589969635, ...
1   "green"  [0.0022163428366184235, -0.006371138617396355,...
2  "yellow"  [-0.012818023562431335, -0.014281628653407097,...
3    "blue"  [-0.008468572981655598, -0.0029912234749644995...
4   "black"  [-0.015700411051511765, -0.018491897732019424,...

In [28]:
len(df['embedding'][0])

1536

In [29]:
a = get_embedding('hello world', engine='text-embedding-ada-002')

In [30]:
len(a)

1536