In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("/Users/ganfeng/Documents/git_repo/ds_interview/dataset/nasa_exoplanet_intelligence.csv")

In [5]:
df.shape

(6150, 31)

In [6]:
df.columns

Index(['planet_name', 'host_star', 'n_stars', 'n_planets', 'discovery_method',
       'disc_year', 'disc_facility', 'orbital_period_days',
       'planet_radius_earth', 'planet_mass_earth', 'equilibrium_temp_k',
       'orbital_eccentricity', 'semi_major_axis_au', 'star_temp_k',
       'star_radius_sun', 'star_mass_sun', 'star_age_gyr',
       'star_surface_gravity', 'star_metallicity', 'dist_from_earth_pc',
       'star_vmag', 'ra', 'dec', 'controversial_flag', 'planet_type',
       'habitable_zone_flag', 'multi_planet_system', 'is_recent_discovery',
       'dist_category', 'star_type', 'orbital_period_cat'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6150 entries, 0 to 6149
Data columns (total 31 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   planet_name           6150 non-null   object
 1   host_star             6150 non-null   object
 2   n_stars               6150 non-null   int64
 3   n_planets             6150 non-null   int64
 4   discovery_method      6150 non-null   object
 5   disc_year             6149 non-null   float64
 6   disc_facility         6150 non-null   object
 7   orbital_period_days   5816 non-null   float64
 8   planet_radius_earth   6100 non-null   float64
 9   planet_mass_earth     6119 non-null   float64
 10  equilibrium_temp_k    4587 non-null   float64
 11  orbital_eccentricity  5212 non-null   float64
 12  semi_major_axis_au    5834 non-null   float64
 13  star_temp_k           5860 non-null   float64
 14  star_radius_sun       5836 non-null   float64
 15  star_mass_sun         6142 non-null   float64
 16  star_age_gyr          4839 non-null   float64
 17  star_surface_gravity  5832 non-null   float64
 18  star_metallicity      5600 non-null   float64
 19  dist_from_earth_pc    6123 non-null   float64
 20  star_vmag             5855 non-null   float64
 21  ra                    6150 non-null   float64
 22  dec                   6150 non-null   float64
 23  controversial_flag    6150 non-null   int64
 24  planet_type           6150 non-null   object
 25  habitable_zone_flag   6150 non-null   bool
 26  multi_planet_system   6150 non-null   bool
 27  is_recent_discovery   6150 non-null   bool
 28  dist_category         6150 non-null   object
 29  star_type             6150 non-null   object
 30  orbital_period_cat    6150 non-null   object
dtypes: bool(3), float64(17), int64(3), object(8)
memory usage: 1.3+ MB

In [8]:
df.head()

,planet_name,host_star,n_stars,n_planets,discovery_method,disc_year,disc_facility,orbital_period_days,planet_radius_earth,planet_mass_earth,...,ra,dec,controversial_flag,planet_type,habitable_zone_flag,multi_planet_system,is_recent_discovery,dist_category,star_type,orbital_period_cat
0,Kepler-1167 b,Kepler-1167,1,1,Transit,2016.0,Kepler,1.003934,1.710000,3.570,...,298.302660,47.693965,0,Super-Earth,False,False,False,Far(500-2kpc),K-type,Short(1-10d)
1,Kepler-1740 b,Kepler-1740,1,1,Transit,2021.0,Kepler,8.172400,3.323214,11.000,...,293.873663,38.922455,0,Mini-Neptune,False,False,True,Far(500-2kpc),G-type(Sun-like),Short(1-10d)
2,Kepler-1581 b,Kepler-1581,1,1,Transit,2016.0,Kepler,6.283855,0.800000,0.437,...,287.371320,39.603623,0,Sub-Earth,False,False,False,Mid(100-500pc),F-type,Short(1-10d)
3,Kepler-644 b,Kepler-644,1,1,Transit,2016.0,Kepler,3.173917,3.150000,10.100,...,295.475702,43.493112,0,Mini-Neptune,False,False,False,Far(500-2kpc),F-type,Short(1-10d)
4,Kepler-1752 b,Kepler-1752,1,1,Transit,2021.0,Kepler,56.358501,4.540605,18.700,...,290.854140,51.222743,0,Neptune-like,False,False,True,Far(500-2kpc),G-type(Sun-like),Medium(10-100d)

In [20]:
df['planet_type'].unique()

array(['Super-Earth', 'Mini-Neptune', 'Sub-Earth', 'Neptune-like',
       'Gas Giant', 'Super-Jupiter', 'Unknown'], dtype=object)

In [21]:
df["planet_type"].nunique()

7

In [37]:
df.nunique()

planet_name             6150
host_star               4582
n_stars                    4
n_planets                  8
discovery_method          11
disc_year                 34
disc_facility             73
orbital_period_days     5802
planet_radius_earth     2136
planet_mass_earth       2817
equilibrium_temp_k      1876
orbital_eccentricity     611
semi_major_axis_au      3536
star_temp_k             2295
star_radius_sun         1808
star_mass_sun           1206
star_age_gyr             662
star_surface_gravity    1250
star_metallicity         618
dist_from_earth_pc      4469
star_vmag               3220
ra                      4579
dec                     4579
controversial_flag         2
planet_type                7
habitable_zone_flag        2
multi_planet_system        2
is_recent_discovery        2
dist_category              5
star_type                  8
orbital_period_cat         6
dtype: int64

In [36]:
df.nunique()["planet_type"]

7

In [39]:
df['discovery_method'].value_counts()

discovery_method
Transit                          4517
Radial Velocity                  1182
Microlensing                      275
Imaging                            94
Transit Timing Variations          39
Eclipse Timing Variations          17
Orbital Brightness Modulation       9
Pulsar Timing                       8
Astrometry                          6
Pulsation Timing Variations         2
Disk Kinematics                     1
Name: count, dtype: int64

In [18]:
# data query using pandas

df_filtered = df.query("n_stars == 1 and orbital_period_days >= 2 and discovery_method in ('Transit', 'Imaging')")

In [16]:
df_filtered["orbital_period_days"].nlargest(10)

2106    402000000.0
4512      8040000.0
2614      7300000.0
433        170000.0
1920        69000.0
5909        44000.0
4213        43500.0
434         37000.0
5046        33000.0
5045        31000.0
Name: orbital_period_days, dtype: float64

In [42]:
# select rows with the largest value of certain field
df.nlargest(10, "orbital_period_days")

,planet_name,host_star,n_stars,n_planets,discovery_method,disc_year,disc_facility,orbital_period_days,planet_radius_earth,planet_mass_earth,...,ra,dec,controversial_flag,planet_type,habitable_zone_flag,multi_planet_system,is_recent_discovery,dist_category,star_type,orbital_period_cat
2106,COCONUTS-2 b,COCONUTS-2 A,1,1,Imaging,2021.0,NASA Infrared Telescope Facility (IRTF),4.020000e+08,12.441969,2542.627256,...,117.300914,-76.702696,0,Gas Giant,False,False,True,Nearby(<100pc),M-type(Red Dwarf),Very-Long(365d+)
4512,CFHTWIR-Oph 98 b,CFHTWIR-Oph 98 A,1,1,Imaging,2021.0,Hubble Space Telescope,8.040000e+06,20.848704,2479.061575,...,246.934277,-23.981150,0,Super-Jupiter,False,False,True,Unknown,M-type(Red Dwarf),Very-Long(365d+)
2614,Oph 11 b,Oph 11,1,1,Imaging,2006.0,Gemini Observatory,7.300000e+06,12.300000,4449.620000,...,245.604961,-24.087222,0,Gas Giant,False,False,False,Mid(100-500pc),M-type(Red Dwarf),Very-Long(365d+)
4918,VHS J125601.92-125723.9 b,VHS J125601.92-125723.9,2,1,Imaging,2015.0,Paranal Observatory,5.800000e+06,13.674956,5085.254512,...,194.008964,-12.956031,0,Gas Giant,False,False,False,Nearby(<100pc),M-type(Red Dwarf),Very-Long(365d+)
4696,b Cen AB b,b Cen A,2,1,Imaging,2021.0,Paranal Observatory,1.790000e+06,12.400000,3464.329636,...,220.489799,-37.793632,0,Gas Giant,False,False,True,Nearby(<100pc),Unknown,Very-Long(365d+)
433,HR 8799 b,HR 8799,1,4,Imaging,2008.0,Gemini Observatory,1.700000e+05,13.000000,2000.000000,...,346.870149,21.134038,0,Gas Giant,False,True,False,Nearby(<100pc),F-type,Very-Long(365d+)
6115,HD 143811 AB b,HD 143811 A,2,1,Imaging,2025.0,Paranal Observatory,1.170000e+05,15.692573,1938.753283,...,240.889197,-30.137157,0,Super-Jupiter,False,False,True,Mid(100-500pc),F-type,Very-Long(365d+)
4934,HIP 81208 C b,HIP 81208 C,3,1,Imaging,2023.0,Paranal Observatory,1.041000e+05,12.300000,4703.860424,...,248.807500,-35.724758,0,Gas Giant,False,False,True,Mid(100-500pc),Unknown,Very-Long(365d+)
4804,HD 105618 c,HD 105618,1,2,Radial Velocity,2022.0,Multiple Observatories,7.711407e+04,11.900000,8419.592330,...,182.402129,11.211569,0,Gas Giant,False,True,True,Nearby(<100pc),G-type(Sun-like),Very-Long(365d+)
555,HD 62364 c,HD 62364,1,2,Radial Velocity,2022.0,Multiple Observatories,7.483995e+04,12.000000,7923.462187,...,113.905266,-75.544271,1,Gas Giant,False,True,True,Nearby(<100pc),F-type,Very-Long(365d+)

In [17]:
df_filtered["orbital_period_days"].nsmallest(10)

0       1.003934
2270    1.005207
2089    1.008035
1051    1.011536
173     1.018707
3135    1.022679
4564    1.025870
1024    1.041878
3280    1.045623
1219    1.052857
Name: orbital_period_days, dtype: float64

In [24]:
# aggregation function

df_1 = df.groupby("planet_type").agg(
    unique_planet_volume = ("planet_name", "nunique"),
    total_planet_volume = ("planet_name", "size"),
    not_null_volume = ("planet_name", "count"),
    planet_radius_earth_avg = ("orbital_period_days", "mean"),
    planet_radius_earth_total = ("planet_radius_earth", "sum"),
    planet_radius_earth_min = ("planet_radius_earth", "min"),
    planet_radius_earth_max = ("planet_radius_earth", "max")
).reset_index().sort_values(by="planet_type", ascending=True)

In [25]:
df_1

,planet_type,unique_planet_volume,total_planet_volume,not_null_volume,planet_radius_earth_avg,planet_radius_earth_total,planet_radius_earth_min,planet_radius_earth_max
0,Gas Giant,1734,1734,1734,280876.019518,20803.348354,6.004346,14.280241
1,Mini-Neptune,2148,2148,2148,30.836407,5348.801413,1.750000,3.490000
2,Neptune-like,479,479,479,62.584315,2093.828526,3.500000,5.990000
3,Sub-Earth,230,230,230,6.055590,186.860227,0.309800,0.996797
4,Super-Earth,1185,1185,1185,31.474659,1647.892365,1.000000,1.746824
5,Super-Jupiter,324,324,324,27144.300902,5555.367491,14.300000,87.205870
6,Unknown,50,50,50,822.441634,0.000000,NaN,NaN

In [ ]:
# another approach for agg function

df.groupby('planet_type')['orbital_period_days'].mean()

planet_type
Gas Giant        280876.019518
Mini-Neptune         30.836407
Neptune-like         62.584315
Sub-Earth             6.055590
Super-Earth          31.474659
Super-Jupiter     27144.300902
Unknown             822.441634
Name: orbital_period_days, dtype: float64

In [ ]:
# selection

df_selected = df[["planet_name", "host_star", "n_stars"]]

In [28]:
# first 100 rows

df_selected = df.loc[0:100, ["planet_name", "host_star", "n_stars"]]

In [31]:
# first 100 rows

df_selected = df.iloc[0:100]

In [29]:
# sort

df_sorted = df.sort_values(by="orbital_period_days", ascending=True)

In [30]:
df_sorted = df.sort_values(by=["orbital_period_days", "planet_radius_earth"], ascending=[True, False], na_position="first")

In [32]:
# check null values

df.isnull().any()

planet_name             False
host_star               False
n_stars                 False
n_planets               False
discovery_method        False
disc_year                True
disc_facility           False
orbital_period_days      True
planet_radius_earth      True
planet_mass_earth        True
equilibrium_temp_k       True
orbital_eccentricity     True
semi_major_axis_au       True
star_temp_k              True
star_radius_sun          True
star_mass_sun            True
star_age_gyr             True
star_surface_gravity     True
star_metallicity         True
dist_from_earth_pc       True
star_vmag                True
ra                      False
dec                     False
controversial_flag      False
planet_type             False
habitable_zone_flag     False
multi_planet_system     False
is_recent_discovery     False
dist_category           False
star_type               False
orbital_period_cat      False
dtype: bool

In [33]:
df.isnull().sum()

planet_name                0
host_star                  0
n_stars                    0
n_planets                  0
discovery_method           0
disc_year                  1
disc_facility              0
orbital_period_days      334
planet_radius_earth       50
planet_mass_earth         31
equilibrium_temp_k      1563
orbital_eccentricity     938
semi_major_axis_au       316
star_temp_k              290
star_radius_sun          314
star_mass_sun              8
star_age_gyr            1311
star_surface_gravity     318
star_metallicity         550
dist_from_earth_pc        27
star_vmag                295
ra                         0
dec                        0
controversial_flag         0
planet_type                0
habitable_zone_flag        0
multi_planet_system        0
is_recent_discovery        0
dist_category              0
star_type                  0
orbital_period_cat         0
dtype: int64

In [34]:
df.isna().any()

planet_name             False
host_star               False
n_stars                 False
n_planets               False
discovery_method        False
disc_year                True
disc_facility           False
orbital_period_days      True
planet_radius_earth      True
planet_mass_earth        True
equilibrium_temp_k       True
orbital_eccentricity     True
semi_major_axis_au       True
star_temp_k              True
star_radius_sun          True
star_mass_sun            True
star_age_gyr             True
star_surface_gravity     True
star_metallicity         True
dist_from_earth_pc       True
star_vmag                True
ra                      False
dec                     False
controversial_flag      False
planet_type             False
habitable_zone_flag     False
multi_planet_system     False
is_recent_discovery     False
dist_category           False
star_type               False
orbital_period_cat      False
dtype: bool

In [35]:
df.isna().sum()

planet_name                0
host_star                  0
n_stars                    0
n_planets                  0
discovery_method           0
disc_year                  1
disc_facility              0
orbital_period_days      334
planet_radius_earth       50
planet_mass_earth         31
equilibrium_temp_k      1563
orbital_eccentricity     938
semi_major_axis_au       316
star_temp_k              290
star_radius_sun          314
star_mass_sun              8
star_age_gyr            1311
star_surface_gravity     318
star_metallicity         550
dist_from_earth_pc        27
star_vmag                295
ra                         0
dec                        0
controversial_flag         0
planet_type                0
habitable_zone_flag        0
multi_planet_system        0
is_recent_discovery        0
dist_category              0
star_type                  0
orbital_period_cat         0
dtype: int64

In [ ]:
# window function: row number, rank, dense rank

df_3 = df.copy()
df_3["row_number"] = df_3["planet_radius_earth"].rank(method="first", ascending=True)
df_3["rank"] = df_3["planet_radius_earth"].rank(method="min", ascending=True)
df_3["dense_rank"] = df_3["planet_radius_earth"].rank(method="dense", ascending=True)

In [45]:
# window function: row number, rank, dense rank - by group

df_4 = df.copy()
df_4["row_number"] = df_4.groupby("planet_type")["planet_radius_earth"].rank(method="first", ascending=True)
df_4["rank"] = df_4.groupby("planet_type")["planet_radius_earth"].rank(method="min", ascending=True)
df_4["dense_rank"] = df_4.groupby("planet_type")["planet_radius_earth"].rank(method="dense", ascending=True)